services:
  - type: web
    name: search-agent-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host=0.0.0.0 --port=8000"
    envVars:
      - key: GOOGLE_API_KEY
        value: AIzaSyDkuhrLpw9Rum3xEtCSXeKqPskd1y2QdDg
      - key: TAVILY_API_KEY
        value: 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
      - key: REDIS_URL
        value: redis://localhost:6379