version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis_memory
    ports:
      - "6379:6379"

  fastapi_app:
    build: .
    container_name: ai_research_agent
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env
